kind: Service
apiVersion: v1
metadata:
  name: fluentd
  namespace: kube-logging
  labels:
    app: fluentd
spec:
  selector:
    app: fluentd
  type: LoadBalancer
  ports:
    - port: 24231
      name: rest
